language: go

go:
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip
  fast_finish: true

install:
  - curl https://glide.sh/get | sh
  - glide install
  - go get -t $(go list ./... | grep -v /vendor/)
  - go get github.com/golang/lint/golint
  - go get github.com/alecthomas/gometalinter
  - go get github.com/client9/misspell/cmd/misspell
  - go get github.com/gordonklaus/ineffassign
  - go get golang.org/x/tools/cmd/goimports
  - go get github.com/tsenart/deadcode

script:
  - gometalinter --disable-all -E vet -E gofmt -E misspell -E ineffassign -E goimports -E deadcode --tests --vendor $(go list ./... | grep -v /vendor/)

notifications:
  email: false